kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: server
        url: http://10.127.253.15:9090
        version: 1
        editable: true